name: Assume role script

on:
  push:
    branches: [ main ]

jobs:
  assume-role:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Execute shell script
        run: bash /etc/actions-runner/assume-role.sh 11111111111 admin_1

    
