name: Terraform Deployment to AWS Account

on:
  push:
    branches: [ main ]
jobs:
  terraform_deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS credentials
        run: |
          aws configure --profile production \
            --AWS_ACCESS_KEY_ID <YOUR_AWS_ACCESS_KEY_ID> \
            --AWS_SECRET_ACCESS_KEY <YOUR_AWS_SECRET_ACCESS_KEY> \
            --region <YOUR_AWS_REGION>
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          auto-approve: true
      - name: Plan Terraform changes
        run: terraform plan
      - name: Apply Terraform changes
        run: terraform apply
      - name: Upload Terraform logs
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: ./terraform.log
