name: Terraform Deployment to AWS Account
env:
  AWS_AccountID: 111111111
  AWS_IAMrole: admin 
on:
  push:
    branches:
      - main  #Change to your branch name
jobs:
  terraform_deploy:
    runs-on: hcl-snadbox-runner
    env:
        steps.run.outputs: false
    steps:
      - uses: actions/checkout@v3
      
      - name: Backing up AWS credentials
        run: cp -r /home/ssm-user/.aws  /home/ssm-user/.aws_bkp 
      - name: Setup AWS credentials 
        run: bash /home/runner/assume-role.sh ${{ env.AWS_AccountID }} ${{ env.AWS_IAMrole }}  > /home/ssm-user/.aws/credentials 
      - name: Backing up AWS credentials
        run: mv  /home/ssm-user/.aws_bkp  /home/ssm-user/.aws   
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          auto-approve: true
      - name: Plan Terraform changes
        run: terraform plan
      - name: Apply Terraform changes
        run: terraform apply
      - name: Upload Terraform logs
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: ./terraform.log
