name: Terraform Deployment to AWS Account
env:
  AWS_AccountID: 111111111
  AWS_IAMrole: admin 
  ROOT_PATH: './s3'
on:
  push:
    branches:
      - main  #Change to your branch name
    tags:
      - deploy-to-production
    paths:
      - s3/**
    
jobs:
  terraform_deploy:
    runs-on: hcl-snadbox-runner
    env:
        steps.run.outputs: false
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup AWS credentials 
        run: bash /home/runner/assume-role.sh ${{ env.AWS_AccountID }} ${{ env.AWS_IAMrole }}  > /tmp/aws_credentials
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          auto-approve: true
      - name: Init Terraform changes
        run: /usr/local/bin/terraform init
        working-directory: ${{ env.ROOT_PATH }}
      - name: Plan Terraform changes
        run: /usr/local/bin/terraform plan -out saved_plan
        working-directory: ${{ env.ROOT_PATH }}
      #################################################
      - name: Submit plan for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        id: submit_plan
        with:
          command: submit
          plan_contents: ${{steps.plan.outputs.stdout}}

    # Snip: send a Slack DM asking somebody to visit `steps.submit_plan.outputs.approval_prompt_url` to approve

      - name: Wait for approval
        uses: jbergknoff/github-action-wait-for-terraform-plan-approval@v1
        with:
          command: wait
          plan_id: ${{steps.submit_plan.outputs.plan_id}}
          timeout-minutes: 10
    #################################################
      - name: Apply Terraform changes
        run: /usr/local/bin/terraform apply -out saved_plan
        working-directory: ${{ env.ROOT_PATH }}
        
      - name: Cleanup AWS credentials
        run: rm -f /tmp/aws_credentials
